HAI 1.2
  I HAS A VAR ITZ 0
  IM IN YR LOOPY UPPIN YR VAR TIL BOTH SAEM VAR AN 10
    BOTH SAEM VAR AN 8
    O RLY?
      YA RLY
        GTFO
    OIC
    VISIBLE SUM OF VAR AN 1
  IM OUTTA YR LOOPY
KTHXBYE
